variables:
  APP_NAME: "course4me"
stages:
  - Build Artifacts
  - Deploy
# Add some job in "Build Artifacts" stage to prepare the artifacts to push along with the docker image.
Deploy to Heroku:
  stage: Deploy
  image: docker:stable
  services:
    - docker:dind
  only:
    - develop
    - master
  when: manual
  script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker build -t registry.heroku.com/$APP_NAME/web .
    - docker push registry.heroku.com/$APP_NAME/web
    - docker run -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli:latest container:release web -a $APP_NAME